### ISSUE TITLE
Bug where editing a client modal and the DOB fields are being transversed  

### ISSUE THREAD

**Issue by RyanNerd** [RyanNerd/rxchart-web#328]
This is getting called every time a DOB field gets focus (not a big deal because clients DOB is rarely edited) but still shouldn't be calling the API when focus moves about.

API Call: `https://domain.com/v1/resident/search`

Body:
```
{
	"where": [
		["FirstName", "=", "PersonsFirstName"],
		["LastName", "=", "PersonsLastName"],
		["DOB_YEAR", "=", 1976],
		["DOB_MONTH", "=", 10],
		["DOB_DAY", "=", "21"],
		["Id", "<>", 1038]
	],
	"withTrashed": true
}
```

**Comment by RyanNerd** [comment]
Also one of the fields is null and shouldn't be:

```
index.js:1 Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    at input
    at http://localhost:3000/static/js/vendors~main.chunk.js:81498:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:80149:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:84260:23
    at http://localhost:3000/static/js/vendors~main.chunk.js:81805:23
    at form
    at http://localhost:3000/static/js/vendors~main.chunk.js:81198:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:85670:27
    at div
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:82735:23
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:118425:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:80989:24
    at DialogTransition
    at http://localhost:3000/static/js/vendors~main.chunk.js:116102:24
    at http://localhost:3000/static/js/vendors~main.chunk.js:82431:23
    at ClientEdit (http://localhost:3000/static/js/main.chunk.js:12019:32)
    at ClientHeader (http://localhost:3000/static/js/main.chunk.js:528:87)
    at Main (http://localhost:3000/static/js/main.chunk.js:958:81)
    at App (http://localhost:3000/static/js/main.chunk.js:363:97)
```
