### ISSUE TITLE
MedicineEdit has input values that are null and it's making React mad

### ISSUE THREAD

**Issue by RyanNerd** [RyanNerd/rxchart-web#339]
```
index.js:1 Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    at input
    at http://localhost:3000/static/js/vendors~main.chunk.js:81498:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:80149:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:84260:23
    at http://localhost:3000/static/js/vendors~main.chunk.js:81805:23
    at form
    at http://localhost:3000/static/js/vendors~main.chunk.js:81198:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:85670:27
    at div
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:82735:23
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:118425:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:80989:24
    at DialogTransition
    at http://localhost:3000/static/js/vendors~main.chunk.js:116102:24
    at http://localhost:3000/static/js/vendors~main.chunk.js:82431:23
    at MedicineEdit (http://localhost:3000/static/js/main.chunk.js:14711:5)
    at ManageOtc (http://localhost:3000/static/js/main.chunk.js:10976:87)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:84777:23
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:118425:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:80989:24
    at http://localhost:3000/static/js/vendors~main.chunk.js:84863:24
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:84777:23
    at TabContainer (http://localhost:3000/static/js/vendors~main.chunk.js:84711:96)
    at Tabs (http://localhost:3000/static/js/vendors~main.chunk.js:85048:96)
    at ManagementPage (http://localhost:3000/static/js/main.chunk.js:10747:112)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:84777:23
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:118425:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:80989:24
    at http://localhost:3000/static/js/vendors~main.chunk.js:84863:24
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:84777:23
    at TabContainer (http://localhost:3000/static/js/vendors~main.chunk.js:84711:96)
    at Tabs (http://localhost:3000/static/js/vendors~main.chunk.js:85048:96)
    at LandingPage (http://localhost:3000/static/js/main.chunk.js:7887:82)
    at Main (http://localhost:3000/static/js/main.chunk.js:979:5)
    at App (http://localhost:3000/static/js/main.chunk.js:363:97)
```

**Comment by RyanNerd** [comment]
Caused by `OtherNames`, `Barcode`, and `Strengh` fields not listed in the great null2stringifcation
