### ISSUE TITLE
DrugLogEdit has an uncontrolled field (null)

### ISSUE THREAD

**Issue by RyanNerd** [RyanNerd/rxchart-web#346]
```
react-dom.development.js:67 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at http://localhost:3000/static/js/bundle.js:33853:23
    at div
    at http://localhost:3000/static/js/bundle.js:32702:23
    at div
    at http://localhost:3000/static/js/bundle.js:35635:23
    at http://localhost:3000/static/js/bundle.js:34164:23
    at form
    at http://localhost:3000/static/js/bundle.js:33548:23
    at div
    at http://localhost:3000/static/js/bundle.js:36808:27
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:34928:23
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:66861:30)
    at http://localhost:3000/static/js/bundle.js:33421:24
    at DialogTransition
    at http://localhost:3000/static/js/bundle.js:64507:24
    at http://localhost:3000/static/js/bundle.js:34620:23
    at DrugLogEdit (http://localhost:3000/static/js/bundle.js:11547:5)
    at RxMedicine (http://localhost:3000/static/js/bundle.js:14976:80)
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:66861:30)
    at http://localhost:3000/static/js/bundle.js:33421:24
    at http://localhost:3000/static/js/bundle.js:36088:24
    at div
    at http://localhost:3000/static/js/bundle.js:36000:23
    at TabContainer (http://localhost:3000/static/js/bundle.js:35933:89)
    at Tabs (http://localhost:3000/static/js/bundle.js:36275:89)
    at div
    at RxPage (http://localhost:3000/static/js/bundle.js:13481:75)
    at div
    at http://localhost:3000/static/js/bundle.js:36000:23
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:66861:30)
    at http://localhost:3000/static/js/bundle.js:33421:24
    at http://localhost:3000/static/js/bundle.js:36088:24
    at div
    at http://localhost:3000/static/js/bundle.js:36000:23
    at TabContainer (http://localhost:3000/static/js/bundle.js:35933:89)
    at Tabs (http://localhost:3000/static/js/bundle.js:36275:89)
    at LandingPage (http://localhost:3000/static/js/bundle.js:6275:75)
    at Main (http://localhost:3000/static/js/bundle.js:727:5)
    at App (http://localhost:3000/static/js/bundle.js:235:90)
printWarning @ react-dom.development.js:67
```

**Comment by RyanNerd** [comment]
I've tried to duplicate this issue a few times but haven't found the circumstances that trigger the warning yet.
