### ISSUE TITLE
Adding new medication (from Manage Rx) prop `title` required in `DropdownButton` but is `undefined`

### ISSUE THREAD

**Issue by RyanNerd** [RyanNerd/rxchart-web#347]
```
react_devtools_backend.js:3973 Warning: Failed prop type: The prop `title` is marked as required in `DropdownButton`, but its value is `undefined`.
    at http://localhost:3000/static/js/bundle.js:33002:20
    at MedDropdown (http://localhost:3000/static/js/bundle.js:6966:5)
    at div
    at http://localhost:3000/static/js/bundle.js:32040:21
    at http://localhost:3000/static/js/bundle.js:34489:23
    at div
    at http://localhost:3000/static/js/bundle.js:31906:22
    at http://localhost:3000/static/js/bundle.js:34423:89
    at MedListGroup (http://localhost:3000/static/js/bundle.js:7138:5)
    at div
    at http://localhost:3000/static/js/bundle.js:32702:23
    at div
    at http://localhost:3000/static/js/bundle.js:35635:23
    at RxMedicine (http://localhost:3000/static/js/bundle.js:14976:80)
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:66861:30)
    at http://localhost:3000/static/js/bundle.js:33421:24
    at http://localhost:3000/static/js/bundle.js:36088:24
    at div
    at http://localhost:3000/static/js/bundle.js:36000:23
    at TabContainer (http://localhost:3000/static/js/bundle.js:35933:89)
    at Tabs (http://localhost:3000/static/js/bundle.js:36275:89)
    at div
    at RxPage (http://localhost:3000/static/js/bundle.js:13481:75)
    at div
    at http://localhost:3000/static/js/bundle.js:36000:23
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:66861:30)
    at http://localhost:3000/static/js/bundle.js:33421:24
    at http://localhost:3000/static/js/bundle.js:36088:24
    at div
    at http://localhost:3000/static/js/bundle.js:36000:23
    at TabContainer (http://localhost:3000/static/js/bundle.js:35933:89)
    at Tabs (http://localhost:3000/static/js/bundle.js:36275:89)
    at LandingPage (http://localhost:3000/static/js/bundle.js:6275:75)
    at Main (http://localhost:3000/static/js/bundle.js:727:5)
    at App (http://localhost:3000/static/js/bundle.js:235:90)
overrideMethod @ react_devtools_backend.js:3973
printWarning @ react-jsx-dev-runtime.development.js:117
error @ react-jsx-dev-runtime.development.js:93
checkPropTypes @ react-jsx-dev-runtime.development.js:620
validatePropTypes @ react-jsx-dev-runtime.development.js:1072
jsxWithValidation @ react-jsx-dev-runtime.development.js:1192
MedDropdown @ MedDropdown.tsx:55
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ use-force-update.js:23
GlobalStateManager.flush @ global-state-manager.js:174
GlobalStateManager.setObject @ global-state-manager.js:337
GlobalStateManager.set @ global-state-manager.js:313
_setGlobal @ set-global.js:6
(anonymous) @ use-global.js:36
saveMedicine @ RxManage.tsx:135
await in saveMedicine (async)
onClose @ RxManage.tsx:285
handleHide @ MedicineEdit.tsx:141
onClick @ MedicineEdit.tsx:432
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

**Comment by RyanNerd** [comment]
I think this is because state isn't managed correctly between the Medication tab and ManageRx tab
